package lifecycle

import (
	"context"
	"errors"
	"fmt"
	"math/rand"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"sync"
	"time"

	"github.com/vibe-agi/hideout/internal/backend"
)

const (
	modelExhaustiveSequenceCount = 180
	modelPersistedReplaySeeds    = 32
	modelConcurrentReplaySeeds   = 32
	modelReplaySteps             = 24
	modelConcurrentWaitBound     = 2 * time.Second
)

var requiredModelEvents = []string{
	"activate",
	"attach",
	"backend-observation-success",
	"backend-observation-unknown",
	"client-crash",
	"daemon-crash",
	"external-boot-change",
	"host-only-handoff",
	"recovery",
	"release",
	"retained-overlay",
	"stop-command-failure",
	"stop-command-success",
	"stop-request",
	"timeout",
	"vm-bound-bridge",
	"workspace-provider-activate",
	"workspace-provider-last-release",
	"workspace-recovery-absence",
	"workspace-recovery-unproved",
	"workspace-view-activate",
	"workspace-view-release",
}

var requiredModelInvariants = []string{
	"commandSuccessRequiresStoppedObservation",
	"dependencyGraphAcyclic",
	"generationIsolation",
	"journalValidAfterEachStep",
	"liveResourceNeverDependsOnReleasedResource",
	"retainedStateDoesNotPin",
	"siblingReleasePreservesOtherOwner",
	"stoppedRootHasNoLiveDependent",
	"unknownStateNeverStops",
	"workspaceResourcesAbsentBeforeStop",
	"workspaceRestartDoesNotReadopt",
	"workspaceSiblingProviderPreserved",
	"workspaceViewHasClosedDependencies",
}

// ModelCheckReport is generated by executing the production lifecycle
// coordinator and reducers. It contains no operator or target data.
type ModelCheckReport struct {
	Schema                    string          `json:"schema"`
	Status                    string          `json:"status"`
	ExhaustiveSequences       int             `json:"exhaustiveSequences"`
	ExploredTransitions       int             `json:"exploredTransitions"`
	ScenarioCount             int             `json:"scenarioCount"`
	PersistedReplaySeeds      int             `json:"persistedReplaySeeds"`
	ConcurrentReplaySeeds     int             `json:"concurrentReplaySeeds"`
	StepsPerPersistedReplay   int             `json:"stepsPerPersistedReplay"`
	ConcurrentWaitBoundMS     int             `json:"concurrentWaitBoundMs"`
	CoveredEvents             []string        `json:"coveredEvents"`
	Invariants                map[string]bool `json:"invariants"`
	JournalValidAfterEachStep bool            `json:"journalValidAfterEachStep"`
	CorruptionRejected        bool            `json:"corruptionRejected"`
	StopsWithLiveClient       int             `json:"stopsWithLiveClient"`
	DuplicateGenerationStops  int             `json:"duplicateGenerationStops"`
}

type modelCounters struct {
	mu                       sync.Mutex
	transitions              int
	scenarios                int
	covered                  map[string]bool
	invariants               map[string]bool
	stopsWithLiveClient      int
	duplicateGenerationStops int
}

// RunBoundedModelCheck executes deterministic finite sequences, persisted
// replay, and bounded concurrent replay against the production coordinator.
func RunBoundedModelCheck() (ModelCheckReport, error) {
	counters := &modelCounters{covered: map[string]bool{}, invariants: map[string]bool{}}
	sequences := modelConstrainedPermutations(
		[]string{"attach-a", "finish-a", "attach-b", "finish-b", "timeout", "boot-2"},
		func(sequence []string) bool {
			return modelIndexOf(sequence, "attach-a") < modelIndexOf(sequence, "finish-a") &&
				modelIndexOf(sequence, "attach-b") < modelIndexOf(sequence, "finish-b")
		},
	)
	if len(sequences) != modelExhaustiveSequenceCount {
		return ModelCheckReport{}, fmt.Errorf("lifecycle model sequence cardinality=%d want %d", len(sequences), modelExhaustiveSequenceCount)
	}
	for _, sequence := range sequences {
		if err := runModelSequence(sequence, counters); err != nil {
			return ModelCheckReport{}, err
		}
	}
	if err := runModelContractScenarios(counters); err != nil {
		return ModelCheckReport{}, err
	}
	if err := runModelPersistedReplays(counters); err != nil {
		return ModelCheckReport{}, err
	}
	if err := runModelConcurrentReplays(counters); err != nil {
		return ModelCheckReport{}, err
	}
	if err := verifyModelCoverage(counters); err != nil {
		return ModelCheckReport{}, err
	}
	report := ModelCheckReport{
		Schema: "hideout.lifecycle-model-evidence/v1", Status: "passed",
		ExhaustiveSequences: modelExhaustiveSequenceCount,
		ExploredTransitions: counters.transitions, ScenarioCount: counters.scenarios,
		PersistedReplaySeeds: modelPersistedReplaySeeds, ConcurrentReplaySeeds: modelConcurrentReplaySeeds,
		StepsPerPersistedReplay: modelReplaySteps, ConcurrentWaitBoundMS: int(modelConcurrentWaitBound / time.Millisecond),
		Invariants: counters.invariants, JournalValidAfterEachStep: counters.invariants["journalValidAfterEachStep"],
		CorruptionRejected: true, StopsWithLiveClient: counters.stopsWithLiveClient,
		DuplicateGenerationStops: counters.duplicateGenerationStops,
	}
	for event := range counters.covered {
		report.CoveredEvents = append(report.CoveredEvents, event)
	}
	sort.Strings(report.CoveredEvents)
	return report, nil
}

// RequiredModelEvents returns the closed event inventory required in emitted
// model evidence.
func RequiredModelEvents() []string {
	return append([]string(nil), requiredModelEvents...)
}

// RequiredModelInvariants returns the closed invariant inventory required in
// emitted model evidence.
func RequiredModelInvariants() []string {
	return append([]string(nil), requiredModelInvariants...)
}

type modelClock struct {
	mu     sync.Mutex
	now    time.Time
	timers []*modelTimer
}

type modelTimer struct {
	clock   *modelClock
	due     time.Time
	fn      func()
	stopped bool
	fired   bool
}

func (t *modelTimer) Stop() bool {
	t.clock.mu.Lock()
	defer t.clock.mu.Unlock()
	active := !t.stopped && !t.fired
	t.stopped = true
	return active
}

func (c *modelClock) after(delay time.Duration, fn func()) timerHandle {
	c.mu.Lock()
	defer c.mu.Unlock()
	timer := &modelTimer{clock: c, due: c.now.Add(delay), fn: fn}
	c.timers = append(c.timers, timer)
	return timer
}

func (c *modelClock) advance(delay time.Duration) {
	c.mu.Lock()
	c.now = c.now.Add(delay)
	var callbacks []func()
	for _, timer := range c.timers {
		if !timer.stopped && !timer.fired && !timer.due.After(c.now) {
			timer.fired = true
			callbacks = append(callbacks, timer.fn)
		}
	}
	c.mu.Unlock()
	for _, callback := range callbacks {
		callback()
	}
}

func (c *modelClock) current() time.Time {
	c.mu.Lock()
	defer c.mu.Unlock()
	return c.now
}

type modelStopBehavior struct {
	mu         sync.Mutex
	mode       string
	active     *int
	stopped    map[uint64]bool
	counters   *modelCounters
	clock      *modelClock
	instance   string
	invocation int
}

func (s *modelStopBehavior) stop(_ context.Context, request StopRequest) (StopResult, error) {
	s.mu.Lock()
	defer s.mu.Unlock()
	s.invocation++
	if s.active != nil && *s.active != 0 {
		s.counters.stopsWithLiveClient++
		return StopResult{}, errors.New("model observed stop with live client")
	}
	if s.stopped[request.Incarnation.StartGeneration] {
		s.counters.duplicateGenerationStops++
		return StopResult{}, errors.New("model observed duplicate generation stop")
	}
	observedAt := s.clock.current()
	switch s.mode {
	case "failure":
		return StopResult{Observation: backend.LifecycleObservation{
			State: backend.LifecycleRunning, InstanceName: s.instance,
			BootID: request.Incarnation.BootID, ObservedAt: observedAt,
		}}, errors.New("injected backend stop failure")
	case "unknown":
		return StopResult{Observation: backend.LifecycleObservation{
			State: backend.LifecycleUnknown, InstanceName: s.instance,
			ObservedAt: observedAt, ReasonCode: "observation-unavailable",
		}}, nil
	default:
		s.stopped[request.Incarnation.StartGeneration] = true
		return StopResult{Observation: backend.LifecycleObservation{
			State: backend.LifecycleStopped, InstanceName: s.instance, ObservedAt: observedAt,
		}}, nil
	}
}

func newModelCoordinator(root, daemonID string, clock *modelClock, enabled bool, stop StopFunc) (*Coordinator, error) {
	return NewCoordinator(CoordinatorOptions{
		Store: JournalStore{Root: root}, DaemonID: daemonID, IdleGrace: DefaultIdleGrace,
		Now: clock.current, AfterFunc: clock.after, Stop: stop, Enabled: enabled,
	})
}

func modelObservation(clock *modelClock, bootID string, state backend.LifecycleState) backend.LifecycleObservation {
	observation := backend.LifecycleObservation{
		State: state, InstanceName: "hideout-model", ObservedAt: clock.current(),
	}
	if state == backend.LifecycleRunning {
		observation.BootID = bootID
	}
	if state == backend.LifecycleUnknown {
		observation.ReasonCode = "inventory-unavailable"
	}
	return observation
}

func modelAttach(coordinator *Coordinator, clock *modelClock, sessionID, bootID string) (Registration, error) {
	registration, err := coordinator.BeginAttach(context.Background(), AttachRequest{
		EnvironmentID: "env-model", InstanceName: "hideout-model", SessionID: sessionID,
		Observation: modelObservation(clock, bootID, backend.LifecycleRunning),
	})
	if err != nil {
		return nil, err
	}
	provider, err := registration.Register(context.Background(), RegistrationSpec{
		Kind: KindWorkspaceHostProvider, ID: "workspace-provider-shared",
		OwnerKind: "manager", OwnerID: "workspace-provider-shared", State: StatePlanned,
		Dependencies: []DependencySpec{{Ref: registration.Root(), StopMode: StopModeDrain}},
		Persistence:  PersistenceEphemeral, ClosePolicy: ClosePreStopDrain, PossibleVMDependency: true,
	})
	if err != nil {
		_ = registration.Finish(context.Background(), err)
		return nil, err
	}
	view, err := registration.Register(context.Background(), RegistrationSpec{
		Kind: KindWorkspaceGuestView, ID: "workspace-view-" + sessionID,
		OwnerKind: "session", OwnerID: sessionID, State: StatePlanned,
		Dependencies: []DependencySpec{
			{Ref: registration.Root(), StopMode: StopModeDrain},
			{Ref: registration.Session(), StopMode: StopModeDrain},
			{Ref: provider, StopMode: StopModeDrain},
		},
		Persistence: PersistenceEphemeral, ClosePolicy: ClosePreStopDrain, PossibleVMDependency: true,
	})
	if err != nil {
		_ = registration.Finish(context.Background(), err)
		return nil, err
	}
	if err := registration.Commit(context.Background()); err != nil {
		_ = registration.Finish(context.Background(), err)
		return nil, err
	}
	if err := registration.BindBoot(context.Background(), bootID); err != nil {
		_ = registration.Finish(context.Background(), err)
		return nil, err
	}
	if err := registration.Transition(context.Background(), provider, StateStarting); err != nil {
		if activeErr := registration.Transition(context.Background(), provider, StateActive); activeErr != nil {
			_ = registration.Finish(context.Background(), err)
			return nil, err
		}
	} else if err := registration.Transition(context.Background(), provider, StateActive); err != nil {
		_ = registration.Finish(context.Background(), err)
		return nil, err
	}
	for _, state := range []ResourceState{StateStarting, StateActive} {
		if err := registration.Transition(context.Background(), view, state); err != nil {
			_ = registration.Finish(context.Background(), err)
			return nil, err
		}
	}
	if err := registration.Transition(context.Background(), registration.Session(), StateActive); err != nil {
		_ = registration.Finish(context.Background(), err)
		return nil, err
	}
	return registration, nil
}

func runModelSequence(sequence []string, counters *modelCounters) error {
	root, err := os.MkdirTemp("", "hideout-lifecycle-model-sequence-")
	if err != nil {
		return err
	}
	defer os.RemoveAll(root)
	if err := os.Chmod(root, 0o700); err != nil {
		return err
	}
	clock := &modelClock{now: time.Date(2026, 7, 16, 5, 0, 0, 0, time.UTC)}
	active := 0
	stopper := &modelStopBehavior{active: &active, stopped: map[uint64]bool{}, counters: counters, clock: clock, instance: "hideout-model"}
	coordinator, err := newModelCoordinator(root, "daemon-model-sequence", clock, true, stopper.stop)
	if err != nil {
		return err
	}
	registrations := map[string]Registration{}
	bootOne := "01234567-89ab-cdef-0123-456789abcdef"
	bootTwo := "aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee"
	for step, event := range sequence {
		switch event {
		case "attach-a", "attach-b":
			client := strings.TrimPrefix(event, "attach-")
			registration, attachErr := modelAttach(coordinator, clock, "ses-"+client, bootOne)
			if attachErr == nil {
				registrations[client] = registration
				active++
				counters.cover("attach", "activate", "workspace-provider-activate", "workspace-view-activate")
			}
		case "finish-a", "finish-b":
			client := strings.TrimPrefix(event, "finish-")
			if registration := registrations[client]; registration != nil {
				if finishErr := registration.Finish(context.Background(), nil); finishErr == nil {
					active--
					counters.cover("release", "workspace-view-release")
					if active != 0 {
						statuses := coordinator.Snapshot()
						if len(statuses) != 1 || statuses[0].Activity != ActivityPinned {
							return fmt.Errorf("sequence %v step %d sibling release lost the other owner: %+v", sequence, step, statuses)
						}
						if !modelStatusHasResource(statuses[0], KindWorkspaceHostProvider, StateActive) {
							return fmt.Errorf("sequence %v step %d sibling release removed shared workspace provider: %+v", sequence, step, statuses)
						}
						counters.passInvariant("siblingReleasePreservesOtherOwner", "workspaceSiblingProviderPreserved")
					} else {
						counters.cover("workspace-provider-last-release")
					}
				}
				delete(registrations, client)
			}
		case "timeout":
			clock.advance(DefaultIdleGrace)
			counters.cover("timeout", "stop-request", "stop-command-success", "backend-observation-success")
		case "boot-2":
			if started, beginErr := coordinator.BeginReconciliation(context.Background(), "env-model"); beginErr == nil && started {
				reconcileErr := coordinator.Reconcile(context.Background(), ReconcileInput{
					EnvironmentID: "env-model", InstanceName: "hideout-model",
					Observation: modelObservation(clock, bootTwo, backend.LifecycleRunning),
				})
				if active != 0 && reconcileErr == nil {
					return fmt.Errorf("sequence %v step %d replaced incarnation with %d active clients", sequence, step, active)
				}
				if reconcileErr == nil {
					counters.cover("external-boot-change", "recovery")
				}
			}
		}
		counters.step()
		if err := validateModelCoordinator(coordinator, counters); err != nil {
			return fmt.Errorf("sequence %v step %d event %s: %w", sequence, step, event, err)
		}
	}
	if err := coordinator.Close(); err != nil {
		return fmt.Errorf("sequence %v close: %w", sequence, err)
	}
	counters.scenario()
	return nil
}

func runModelContractScenarios(counters *modelCounters) error {
	if err := runModelResourceAndSuccessfulStop(counters); err != nil {
		return err
	}
	for _, mode := range []string{"failure", "unknown"} {
		if err := runModelUnprovedStop(mode, counters); err != nil {
			return err
		}
	}
	if err := runModelCrashAndRecovery(counters); err != nil {
		return err
	}
	if err := runModelClientCrash(counters); err != nil {
		return err
	}
	return nil
}

func runModelResourceAndSuccessfulStop(counters *modelCounters) error {
	root, err := os.MkdirTemp("", "hideout-lifecycle-model-resource-")
	if err != nil {
		return err
	}
	defer os.RemoveAll(root)
	_ = os.Chmod(root, 0o700)
	clock := &modelClock{now: time.Date(2026, 7, 16, 6, 0, 0, 0, time.UTC)}
	active := 1
	stopper := &modelStopBehavior{active: &active, stopped: map[uint64]bool{}, counters: counters, clock: clock, instance: "hideout-model"}
	coordinator, err := newModelCoordinator(root, "daemon-model-resource", clock, true, stopper.stop)
	if err != nil {
		return err
	}
	registration, err := modelAttach(coordinator, clock, "ses-resource", "01234567-89ab-cdef-0123-456789abcdef")
	if err != nil {
		return err
	}
	bridge, err := registration.Register(context.Background(), RegistrationSpec{
		Kind: KindRunBridge, ID: "bridge-resource", OwnerKind: "session", State: StatePlanned,
		Dependencies: []DependencySpec{{Ref: registration.Root(), StopMode: StopModePin}, {Ref: registration.Session(), StopMode: StopModeDrain}},
		Persistence:  PersistenceEphemeral, ClosePolicy: ClosePreStopDrain, PossibleVMDependency: true,
	})
	if err != nil {
		return err
	}
	for _, state := range []ResourceState{StateStarting, StateActive} {
		if err := registration.Transition(context.Background(), bridge, state); err != nil {
			return err
		}
	}
	if err := registration.RecordFact(context.Background(), FactSpec{Kind: KindHostFSStaged, ID: "staged-resource", Class: FactRetained}); err != nil {
		return err
	}
	if err := registration.RecordFact(context.Background(), FactSpec{Kind: KindHostAppHandoff, ID: "handoff-resource", Class: FactHandoff}); err != nil {
		return err
	}
	counters.cover("attach", "activate", "vm-bound-bridge", "retained-overlay", "host-only-handoff", "workspace-provider-activate", "workspace-view-activate")
	if err := validateModelCoordinator(coordinator, counters); err != nil {
		return err
	}
	if err := registration.Release(context.Background(), bridge, nil); err != nil {
		return err
	}
	active = 0
	if err := registration.Finish(context.Background(), nil); err != nil {
		return err
	}
	counters.cover("release", "workspace-view-release", "workspace-provider-last-release")
	clock.advance(DefaultIdleGrace)
	counters.cover("timeout", "stop-request", "stop-command-success", "backend-observation-success")
	statuses := coordinator.Snapshot()
	if len(statuses) != 1 || statuses[0].Activity != ActivityStopped || len(statuses[0].Retained) != 1 || len(statuses[0].Handoffs) != 1 {
		return fmt.Errorf("successful stop did not preserve independent facts: %+v", statuses)
	}
	counters.passInvariant("retainedStateDoesNotPin", "stoppedRootHasNoLiveDependent", "workspaceResourcesAbsentBeforeStop")
	if err := validateModelCoordinator(coordinator, counters); err != nil {
		return err
	}
	if err := coordinator.Close(); err != nil {
		return err
	}
	counters.scenario()
	return nil
}

func runModelUnprovedStop(mode string, counters *modelCounters) error {
	root, err := os.MkdirTemp("", "hideout-lifecycle-model-stop-")
	if err != nil {
		return err
	}
	defer os.RemoveAll(root)
	_ = os.Chmod(root, 0o700)
	clock := &modelClock{now: time.Date(2026, 7, 16, 7, 0, 0, 0, time.UTC)}
	active := 1
	stopper := &modelStopBehavior{mode: mode, active: &active, stopped: map[uint64]bool{}, counters: counters, clock: clock, instance: "hideout-model"}
	coordinator, err := newModelCoordinator(root, "daemon-model-stop-"+mode, clock, true, stopper.stop)
	if err != nil {
		return err
	}
	registration, err := modelAttach(coordinator, clock, "ses-stop-"+mode, "01234567-89ab-cdef-0123-456789abcdef")
	if err != nil {
		return err
	}
	active = 0
	if err := registration.Finish(context.Background(), nil); err != nil {
		return err
	}
	clock.advance(DefaultIdleGrace)
	statuses := coordinator.Snapshot()
	if len(statuses) != 1 || statuses[0].Activity == ActivityStopped {
		return fmt.Errorf("%s stop reached stopped without a stopped observation: %+v", mode, statuses)
	}
	if mode == "failure" {
		counters.cover("stop-command-failure")
	} else {
		counters.cover("backend-observation-unknown")
		counters.passInvariant("commandSuccessRequiresStoppedObservation", "unknownStateNeverStops")
	}
	counters.cover("stop-request", "timeout")
	if err := validateModelCoordinator(coordinator, counters); err != nil {
		return err
	}
	if err := coordinator.Close(); err != nil {
		return err
	}
	counters.scenario()
	return nil
}

func runModelCrashAndRecovery(counters *modelCounters) error {
	root, err := os.MkdirTemp("", "hideout-lifecycle-model-recovery-")
	if err != nil {
		return err
	}
	defer os.RemoveAll(root)
	_ = os.Chmod(root, 0o700)
	clock := &modelClock{now: time.Date(2026, 7, 16, 8, 0, 0, 0, time.UTC)}
	first, err := newModelCoordinator(root, "daemon-model-before-crash", clock, false, nil)
	if err != nil {
		return err
	}
	_, err = modelAttach(first, clock, "ses-recovery", "01234567-89ab-cdef-0123-456789abcdef")
	if err != nil {
		return err
	}
	if err := first.Close(); err != nil {
		return err
	}
	counters.cover("daemon-crash")
	second, err := newModelCoordinator(root, "daemon-model-after-crash", clock, false, nil)
	if err != nil {
		return err
	}
	if err := second.Reconcile(context.Background(), ReconcileInput{
		EnvironmentID: "env-model", InstanceName: "hideout-model",
		Observation: modelObservation(clock, "", backend.LifecycleUnknown),
	}); err != nil {
		return err
	}
	statuses := second.Snapshot()
	if len(statuses) != 1 || statuses[0].Activity != ActivityBlocked || !modelStatusHasResource(statuses[0], KindWorkspaceGuestView, StateOrphaned) {
		return fmt.Errorf("workspace restart uncertainty did not remain orphaned: %+v", statuses)
	}
	counters.cover("backend-observation-unknown", "workspace-recovery-unproved")
	if err := second.Reconcile(context.Background(), ReconcileInput{
		EnvironmentID: "env-model", InstanceName: "hideout-model",
		Observation: modelObservation(clock, "01234567-89ab-cdef-0123-456789abcdef", backend.LifecycleRunning),
	}); err != nil {
		return err
	}
	statuses = second.Snapshot()
	if len(statuses) != 1 || modelStatusHasResource(statuses[0], KindWorkspaceHostProvider, "") || modelStatusHasResource(statuses[0], KindWorkspaceGuestView, "") {
		return fmt.Errorf("workspace restart re-adopted prior provider state: %+v", statuses)
	}
	if _, available := second.ActiveAttachObservation(context.Background(), "env-model", "hideout-model"); available {
		return errors.New("workspace restart produced attach authority without a new registration")
	}
	counters.cover("backend-observation-success", "recovery", "workspace-recovery-absence")
	counters.passInvariant("workspaceRestartDoesNotReadopt")
	if err := second.Reconcile(context.Background(), ReconcileInput{
		EnvironmentID: "env-model", InstanceName: "hideout-model",
		Observation: modelObservation(clock, "aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee", backend.LifecycleRunning),
	}); err != nil {
		return err
	}
	counters.cover("external-boot-change")
	if err := validateModelCoordinator(second, counters); err != nil {
		return err
	}
	if err := second.Close(); err != nil {
		return err
	}
	counters.scenario()
	return nil
}

func runModelClientCrash(counters *modelCounters) error {
	root, err := os.MkdirTemp("", "hideout-lifecycle-model-client-crash-")
	if err != nil {
		return err
	}
	defer os.RemoveAll(root)
	_ = os.Chmod(root, 0o700)
	clock := &modelClock{now: time.Date(2026, 7, 16, 9, 0, 0, 0, time.UTC)}
	coordinator, err := newModelCoordinator(root, "daemon-model-client-crash", clock, true, nil)
	if err != nil {
		return err
	}
	registration, err := modelAttach(coordinator, clock, "ses-client-crash", "01234567-89ab-cdef-0123-456789abcdef")
	if err != nil {
		return err
	}
	if err := registration.Finish(context.Background(), errors.New("injected client cleanup loss")); err != nil {
		return err
	}
	counters.cover("client-crash")
	statuses := coordinator.Snapshot()
	if len(statuses) != 1 || statuses[0].Activity != ActivityBlocked || len(statuses[0].Orphans) == 0 {
		return fmt.Errorf("client crash did not remain fail-closed: %+v", statuses)
	}
	if err := validateModelCoordinator(coordinator, counters); err != nil {
		return err
	}
	if err := coordinator.Close(); err != nil {
		return err
	}
	counters.scenario()
	return nil
}

func runModelPersistedReplays(counters *modelCounters) error {
	random := rand.New(rand.NewSource(36036017))
	for scenario := 0; scenario < modelPersistedReplaySeeds; scenario++ {
		seed := random.Int63()
		if err := runOneModelPersistedReplay(seed, scenario == modelPersistedReplaySeeds-1, counters); err != nil {
			return err
		}
	}
	return nil
}

func runOneModelPersistedReplay(seed int64, corrupt bool, counters *modelCounters) error {
	random := rand.New(rand.NewSource(seed))
	root, err := os.MkdirTemp("", "hideout-lifecycle-model-replay-")
	if err != nil {
		return err
	}
	defer os.RemoveAll(root)
	_ = os.Chmod(root, 0o700)
	clock := &modelClock{now: time.Date(2026, 7, 16, 10, 0, 0, 0, time.UTC)}
	store := JournalStore{Root: root}
	coordinator, err := newModelCoordinator(root, "daemon-model-replay-0", clock, false, nil)
	if err != nil {
		return err
	}
	bootID := "01234567-89ab-cdef-0123-456789abcdef"
	if err := coordinator.Reconcile(context.Background(), ReconcileInput{
		EnvironmentID: "env-model", InstanceName: "hideout-model", Observation: modelObservation(clock, bootID, backend.LifecycleRunning),
	}); err != nil {
		return err
	}
	registrations := map[string]Registration{}
	for step := 0; step < modelReplaySteps; step++ {
		client := fmt.Sprintf("ses-%d", random.Intn(2))
		switch random.Intn(6) {
		case 0:
			if registrations[client] == nil {
				if registration, attachErr := modelAttach(coordinator, clock, client, bootID); attachErr == nil {
					registrations[client] = registration
				}
			}
		case 1:
			if registration := registrations[client]; registration != nil {
				_ = registration.Finish(context.Background(), nil)
				delete(registrations, client)
			}
		case 2:
			clock.advance(time.Duration(random.Intn(int(DefaultIdleGrace/time.Millisecond)+1)) * time.Millisecond)
		case 3:
			_ = coordinator.Close()
			registrations = map[string]Registration{}
			coordinator, err = newModelCoordinator(root, fmt.Sprintf("daemon-model-replay-%d", step+1), clock, false, nil)
			if err != nil {
				return err
			}
			_ = coordinator.Reconcile(context.Background(), ReconcileInput{
				EnvironmentID: "env-model", InstanceName: "hideout-model", Observation: modelObservation(clock, bootID, backend.LifecycleRunning),
			})
		case 4:
			_ = coordinator.Reconcile(context.Background(), ReconcileInput{
				EnvironmentID: "env-model", InstanceName: "hideout-model", Observation: modelObservation(clock, "", backend.LifecycleUnknown),
			})
		case 5:
			_ = coordinator.Reconcile(context.Background(), ReconcileInput{
				EnvironmentID: "env-model", InstanceName: "hideout-model", Observation: modelObservation(clock, bootID, backend.LifecycleRunning),
			})
		}
		counters.step()
		if loadErr := validateModelStore(store, counters); loadErr != nil {
			return fmt.Errorf("persisted replay seed=%d step=%d: %w", seed, step, loadErr)
		}
	}
	_ = coordinator.Close()
	counters.scenario()
	if !corrupt {
		return nil
	}
	dir, err := store.environmentDir("env-model", false)
	if err != nil {
		return err
	}
	if err := os.WriteFile(filepath.Join(dir, journalFileName), []byte("{\"schema\":"), 0o600); err != nil {
		return err
	}
	if _, err := store.Load("env-model"); err == nil {
		return errors.New("corrupt lifecycle journal was accepted")
	}
	return nil
}

func runModelConcurrentReplays(counters *modelCounters) error {
	for seed := int64(0); seed < modelConcurrentReplaySeeds; seed++ {
		if err := runOneModelConcurrentReplay(seed+36037000, counters); err != nil {
			return err
		}
	}
	return nil
}

func runOneModelConcurrentReplay(seed int64, counters *modelCounters) error {
	root, err := os.MkdirTemp("", "hideout-lifecycle-model-concurrent-")
	if err != nil {
		return err
	}
	defer os.RemoveAll(root)
	_ = os.Chmod(root, 0o700)
	clock := &modelClock{now: time.Date(2026, 7, 16, 11, 0, 0, 0, time.UTC)}
	coordinator, err := newModelCoordinator(root, fmt.Sprintf("daemon-model-concurrent-%d", seed), clock, false, nil)
	if err != nil {
		return err
	}
	if err := coordinator.Reconcile(context.Background(), ReconcileInput{
		EnvironmentID: "env-model", InstanceName: "hideout-model",
		Observation: modelObservation(clock, "01234567-89ab-cdef-0123-456789abcdef", backend.LifecycleRunning),
	}); err != nil {
		return err
	}
	start := make(chan struct{})
	var wg sync.WaitGroup
	for index := 0; index < 4; index++ {
		index := index
		wg.Add(1)
		go func() {
			defer wg.Done()
			<-start
			switch index {
			case 0, 1:
				registration, attachErr := modelAttach(coordinator, clock, fmt.Sprintf("ses-concurrent-%d", index), "01234567-89ab-cdef-0123-456789abcdef")
				if attachErr == nil {
					_ = registration.Finish(context.Background(), nil)
				}
			case 2:
				clock.advance(DefaultIdleGrace)
			case 3:
				_ = coordinator.Reconcile(context.Background(), ReconcileInput{
					EnvironmentID: "env-model", InstanceName: "hideout-model",
					Observation: modelObservation(clock, "aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee", backend.LifecycleRunning),
				})
			}
		}()
	}
	close(start)
	done := make(chan struct{})
	go func() { wg.Wait(); close(done) }()
	select {
	case <-done:
	case <-time.After(modelConcurrentWaitBound):
		return fmt.Errorf("concurrent lifecycle replay seed=%d exceeded %s", seed, modelConcurrentWaitBound)
	}
	if err := validateModelStore(JournalStore{Root: root}, counters); err != nil {
		return fmt.Errorf("concurrent replay seed=%d: %w", seed, err)
	}
	_ = coordinator.Close()
	counters.scenario()
	return nil
}

func validateModelStore(store JournalStore, counters *modelCounters) error {
	journal, err := store.Load("env-model")
	if err != nil {
		return err
	}
	return validateModelJournal(journal, counters)
}

func validateModelCoordinator(coordinator *Coordinator, counters *modelCounters) error {
	coordinator.mu.Lock()
	state := coordinator.environments["env-model"]
	if state == nil {
		coordinator.mu.Unlock()
		return nil
	}
	journal := state.journal
	observation := state.observation
	coordinator.mu.Unlock()
	if err := validateModelJournal(journal, counters); err != nil {
		return err
	}
	if journal.Incarnation != nil && observation.State == backend.LifecycleUnknown {
		evaluation, err := EvaluateAutoStop(EvaluationInput{
			Incarnation: *journal.Incarnation, Resources: journal.Resources, Observation: observation,
			GraceExpired: true, ReconciliationComplete: journal.Reconciliation.State == "complete",
			CurrentDaemonOwnsAttempt: true,
		})
		if err == nil && evaluation.Allowed {
			return errors.New("unknown backend observation allowed stop")
		}
		counters.passInvariant("unknownStateNeverStops")
	}
	return nil
}

func validateModelJournal(journal Journal, counters *modelCounters) error {
	if err := journal.Validate(); err != nil {
		return err
	}
	counters.passInvariant("journalValidAfterEachStep")
	if err := ValidateGraph(journal.Resources, true); err != nil {
		return err
	}
	counters.passInvariant("dependencyGraphAcyclic")
	byKey := map[string]Resource{}
	for _, resource := range journal.Resources {
		if resource.Ref.Generation != journal.StartGeneration || resource.Owner.Generation != journal.StartGeneration {
			return errors.New("resource from another generation remained authoritative")
		}
		byKey[resource.Ref.Key()] = resource
	}
	counters.passInvariant("generationIsolation")
	for _, resource := range journal.Resources {
		if !resource.IsPossiblyLive() {
			continue
		}
		for _, dependency := range resource.Dependencies {
			if byKey[dependency.Ref.Key()].State == StateReleased {
				return errors.New("live resource depends on released resource")
			}
		}
	}
	counters.passInvariant("liveResourceNeverDependsOnReleasedResource")
	for _, resource := range journal.Resources {
		if resource.Ref.Kind != KindWorkspaceGuestView {
			continue
		}
		dependencies := map[ResourceKind]bool{}
		for _, dependency := range resource.Dependencies {
			dependencies[dependency.Ref.Kind] = dependency.StopMode == StopModeDrain
			if _, ok := byKey[dependency.Ref.Key()]; !ok {
				return errors.New("workspace view dependency is absent")
			}
		}
		for _, kind := range []ResourceKind{KindBackendIncarnation, KindRunSession, KindWorkspaceHostProvider} {
			if !dependencies[kind] {
				return fmt.Errorf("workspace view lacks closed dependency %s", kind)
			}
		}
		counters.passInvariant("workspaceViewHasClosedDependencies")
	}
	return nil
}

func modelStatusHasResource(status Status, kind ResourceKind, state ResourceState) bool {
	for _, list := range [][]ResourceSummary{status.Pins, status.Drains, status.Orphans} {
		for _, resource := range list {
			if resource.Kind == kind && (state == "" || resource.State == state) {
				return true
			}
		}
	}
	return false
}

func verifyModelCoverage(counters *modelCounters) error {
	for _, event := range requiredModelEvents {
		if !counters.covered[event] {
			return fmt.Errorf("lifecycle model did not execute required event %q", event)
		}
	}
	for _, invariant := range requiredModelInvariants {
		if !counters.invariants[invariant] {
			return fmt.Errorf("lifecycle model invariant failed: %s", invariant)
		}
	}
	if counters.stopsWithLiveClient != 0 || counters.duplicateGenerationStops != 0 {
		return errors.New("lifecycle model observed an unsafe stop")
	}
	return nil
}

func (c *modelCounters) cover(events ...string) {
	c.mu.Lock()
	defer c.mu.Unlock()
	for _, event := range events {
		c.covered[event] = true
	}
}

func (c *modelCounters) step() {
	c.mu.Lock()
	c.transitions++
	c.mu.Unlock()
}

func (c *modelCounters) scenario() {
	c.mu.Lock()
	c.scenarios++
	c.mu.Unlock()
}

func (c *modelCounters) passInvariant(names ...string) {
	c.mu.Lock()
	for _, name := range names {
		c.invariants[name] = true
	}
	c.mu.Unlock()
}

func modelConstrainedPermutations(values []string, keep func([]string) bool) [][]string {
	var out [][]string
	working := append([]string(nil), values...)
	var visit func(int)
	visit = func(index int) {
		if index == len(working) {
			candidate := append([]string(nil), working...)
			if keep(candidate) {
				out = append(out, candidate)
			}
			return
		}
		for next := index; next < len(working); next++ {
			working[index], working[next] = working[next], working[index]
			visit(index + 1)
			working[index], working[next] = working[next], working[index]
		}
	}
	visit(0)
	return out
}

func modelIndexOf(values []string, value string) int {
	for index, candidate := range values {
		if candidate == value {
			return index
		}
	}
	return len(values)
}
