// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type fileObserverExecutionRef struct {
	_            structs.HostLayout
	Pid          uint32
	_            [4]byte
	ExecSequence uint64
}

type fileObserverFileCollectorCounters struct {
	_                structs.HostLayout
	MatchedEvents    uint64
	ReservedEvents   uint64
	RingbufDrops     uint64
	StateDrops       uint64
	PathFailures     uint64
	IdentityFailures uint64
}

type fileObserverFileMetadata struct {
	_         structs.HostLayout
	Device    uint64
	Inode     uint64
	FileType  uint32
	Flags     uint32
	Created   uint32
	Announced uint32
	Path      [512]int8
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	fileObserverMapExecSequences                = "exec_sequences"
	fileObserverMapFileCounters                 = "file_counters"
	fileObserverMapFileMetadataScratch          = "file_metadata_scratch"
	fileObserverMapFileObservationEvents        = "file_observation_events"
	fileObserverMapMmapLengths                  = "mmap_lengths"
	fileObserverMapObservedFiles                = "observed_files"
	fileObserverMapObserverSequences            = "observer_sequences"
	fileObserverProgHideoutCaptureMmapLength    = "hideout_capture_mmap_length"
	fileObserverProgHideoutCleanupFileThread    = "hideout_cleanup_file_thread"
	fileObserverProgHideoutForgetFile           = "hideout_forget_file"
	fileObserverProgHideoutForgetMmapLength     = "hideout_forget_mmap_length"
	fileObserverProgHideoutObserveCopyFileRange = "hideout_observe_copy_file_range"
	fileObserverProgHideoutObserveFileOpen      = "hideout_observe_file_open"
	fileObserverProgHideoutObserveFileTruncate  = "hideout_observe_file_truncate"
	fileObserverProgHideoutObserveMmapFile      = "hideout_observe_mmap_file"
	fileObserverProgHideoutObservePathChmod     = "hideout_observe_path_chmod"
	fileObserverProgHideoutObservePathChown     = "hideout_observe_path_chown"
	fileObserverProgHideoutObservePathLink      = "hideout_observe_path_link"
	fileObserverProgHideoutObservePathMkdir     = "hideout_observe_path_mkdir"
	fileObserverProgHideoutObservePathRename    = "hideout_observe_path_rename"
	fileObserverProgHideoutObservePathRmdir     = "hideout_observe_path_rmdir"
	fileObserverProgHideoutObservePathSymlink   = "hideout_observe_path_symlink"
	fileObserverProgHideoutObservePathTruncate  = "hideout_observe_path_truncate"
	fileObserverProgHideoutObservePathUnlink    = "hideout_observe_path_unlink"
	fileObserverProgHideoutObserveVfsRead       = "hideout_observe_vfs_read"
	fileObserverProgHideoutObserveVfsReadv      = "hideout_observe_vfs_readv"
	fileObserverProgHideoutObserveVfsWrite      = "hideout_observe_vfs_write"
	fileObserverProgHideoutObserveVfsWritev     = "hideout_observe_vfs_writev"
	fileObserverVarFileTargetCgroupId           = "file_target_cgroup_id"
)

// loadFileObserver returns the embedded CollectionSpec for fileObserver.
func loadFileObserver() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_FileObserverBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load fileObserver: %w", err)
	}

	return spec, err
}

// loadFileObserverObjects loads fileObserver and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*fileObserverObjects
//	*fileObserverPrograms
//	*fileObserverMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadFileObserverObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadFileObserver()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// fileObserverSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type fileObserverSpecs struct {
	fileObserverProgramSpecs
	fileObserverMapSpecs
	fileObserverVariableSpecs
}

// fileObserverProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type fileObserverProgramSpecs struct {
	HideoutCaptureMmapLength    *ebpf.ProgramSpec `ebpf:"hideout_capture_mmap_length"`
	HideoutCleanupFileThread    *ebpf.ProgramSpec `ebpf:"hideout_cleanup_file_thread"`
	HideoutForgetFile           *ebpf.ProgramSpec `ebpf:"hideout_forget_file"`
	HideoutForgetMmapLength     *ebpf.ProgramSpec `ebpf:"hideout_forget_mmap_length"`
	HideoutObserveCopyFileRange *ebpf.ProgramSpec `ebpf:"hideout_observe_copy_file_range"`
	HideoutObserveFileOpen      *ebpf.ProgramSpec `ebpf:"hideout_observe_file_open"`
	HideoutObserveFileTruncate  *ebpf.ProgramSpec `ebpf:"hideout_observe_file_truncate"`
	HideoutObserveMmapFile      *ebpf.ProgramSpec `ebpf:"hideout_observe_mmap_file"`
	HideoutObservePathChmod     *ebpf.ProgramSpec `ebpf:"hideout_observe_path_chmod"`
	HideoutObservePathChown     *ebpf.ProgramSpec `ebpf:"hideout_observe_path_chown"`
	HideoutObservePathLink      *ebpf.ProgramSpec `ebpf:"hideout_observe_path_link"`
	HideoutObservePathMkdir     *ebpf.ProgramSpec `ebpf:"hideout_observe_path_mkdir"`
	HideoutObservePathRename    *ebpf.ProgramSpec `ebpf:"hideout_observe_path_rename"`
	HideoutObservePathRmdir     *ebpf.ProgramSpec `ebpf:"hideout_observe_path_rmdir"`
	HideoutObservePathSymlink   *ebpf.ProgramSpec `ebpf:"hideout_observe_path_symlink"`
	HideoutObservePathTruncate  *ebpf.ProgramSpec `ebpf:"hideout_observe_path_truncate"`
	HideoutObservePathUnlink    *ebpf.ProgramSpec `ebpf:"hideout_observe_path_unlink"`
	HideoutObserveVfsRead       *ebpf.ProgramSpec `ebpf:"hideout_observe_vfs_read"`
	HideoutObserveVfsReadv      *ebpf.ProgramSpec `ebpf:"hideout_observe_vfs_readv"`
	HideoutObserveVfsWrite      *ebpf.ProgramSpec `ebpf:"hideout_observe_vfs_write"`
	HideoutObserveVfsWritev     *ebpf.ProgramSpec `ebpf:"hideout_observe_vfs_writev"`
}

// fileObserverMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type fileObserverMapSpecs struct {
	ExecSequences         *ebpf.MapSpec `ebpf:"exec_sequences"`
	FileCounters          *ebpf.MapSpec `ebpf:"file_counters"`
	FileMetadataScratch   *ebpf.MapSpec `ebpf:"file_metadata_scratch"`
	FileObservationEvents *ebpf.MapSpec `ebpf:"file_observation_events"`
	MmapLengths           *ebpf.MapSpec `ebpf:"mmap_lengths"`
	ObservedFiles         *ebpf.MapSpec `ebpf:"observed_files"`
	ObserverSequences     *ebpf.MapSpec `ebpf:"observer_sequences"`
}

// fileObserverVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type fileObserverVariableSpecs struct {
	FileTargetCgroupId *ebpf.VariableSpec `ebpf:"file_target_cgroup_id"`
}

// fileObserverObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadFileObserverObjects or ebpf.CollectionSpec.LoadAndAssign.
type fileObserverObjects struct {
	fileObserverPrograms
	fileObserverMaps
	fileObserverVariables
}

func (o *fileObserverObjects) Close() error {
	return _FileObserverClose(
		&o.fileObserverPrograms,
		&o.fileObserverMaps,
	)
}

// fileObserverMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadFileObserverObjects or ebpf.CollectionSpec.LoadAndAssign.
type fileObserverMaps struct {
	ExecSequences         *ebpf.Map `ebpf:"exec_sequences"`
	FileCounters          *ebpf.Map `ebpf:"file_counters"`
	FileMetadataScratch   *ebpf.Map `ebpf:"file_metadata_scratch"`
	FileObservationEvents *ebpf.Map `ebpf:"file_observation_events"`
	MmapLengths           *ebpf.Map `ebpf:"mmap_lengths"`
	ObservedFiles         *ebpf.Map `ebpf:"observed_files"`
	ObserverSequences     *ebpf.Map `ebpf:"observer_sequences"`
}

func (m *fileObserverMaps) Close() error {
	return _FileObserverClose(
		m.ExecSequences,
		m.FileCounters,
		m.FileMetadataScratch,
		m.FileObservationEvents,
		m.MmapLengths,
		m.ObservedFiles,
		m.ObserverSequences,
	)
}

// fileObserverVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadFileObserverObjects or ebpf.CollectionSpec.LoadAndAssign.
type fileObserverVariables struct {
	FileTargetCgroupId *ebpf.Variable `ebpf:"file_target_cgroup_id"`
}

// fileObserverPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadFileObserverObjects or ebpf.CollectionSpec.LoadAndAssign.
type fileObserverPrograms struct {
	HideoutCaptureMmapLength    *ebpf.Program `ebpf:"hideout_capture_mmap_length"`
	HideoutCleanupFileThread    *ebpf.Program `ebpf:"hideout_cleanup_file_thread"`
	HideoutForgetFile           *ebpf.Program `ebpf:"hideout_forget_file"`
	HideoutForgetMmapLength     *ebpf.Program `ebpf:"hideout_forget_mmap_length"`
	HideoutObserveCopyFileRange *ebpf.Program `ebpf:"hideout_observe_copy_file_range"`
	HideoutObserveFileOpen      *ebpf.Program `ebpf:"hideout_observe_file_open"`
	HideoutObserveFileTruncate  *ebpf.Program `ebpf:"hideout_observe_file_truncate"`
	HideoutObserveMmapFile      *ebpf.Program `ebpf:"hideout_observe_mmap_file"`
	HideoutObservePathChmod     *ebpf.Program `ebpf:"hideout_observe_path_chmod"`
	HideoutObservePathChown     *ebpf.Program `ebpf:"hideout_observe_path_chown"`
	HideoutObservePathLink      *ebpf.Program `ebpf:"hideout_observe_path_link"`
	HideoutObservePathMkdir     *ebpf.Program `ebpf:"hideout_observe_path_mkdir"`
	HideoutObservePathRename    *ebpf.Program `ebpf:"hideout_observe_path_rename"`
	HideoutObservePathRmdir     *ebpf.Program `ebpf:"hideout_observe_path_rmdir"`
	HideoutObservePathSymlink   *ebpf.Program `ebpf:"hideout_observe_path_symlink"`
	HideoutObservePathTruncate  *ebpf.Program `ebpf:"hideout_observe_path_truncate"`
	HideoutObservePathUnlink    *ebpf.Program `ebpf:"hideout_observe_path_unlink"`
	HideoutObserveVfsRead       *ebpf.Program `ebpf:"hideout_observe_vfs_read"`
	HideoutObserveVfsReadv      *ebpf.Program `ebpf:"hideout_observe_vfs_readv"`
	HideoutObserveVfsWrite      *ebpf.Program `ebpf:"hideout_observe_vfs_write"`
	HideoutObserveVfsWritev     *ebpf.Program `ebpf:"hideout_observe_vfs_writev"`
}

func (p *fileObserverPrograms) Close() error {
	return _FileObserverClose(
		p.HideoutCaptureMmapLength,
		p.HideoutCleanupFileThread,
		p.HideoutForgetFile,
		p.HideoutForgetMmapLength,
		p.HideoutObserveCopyFileRange,
		p.HideoutObserveFileOpen,
		p.HideoutObserveFileTruncate,
		p.HideoutObserveMmapFile,
		p.HideoutObservePathChmod,
		p.HideoutObservePathChown,
		p.HideoutObservePathLink,
		p.HideoutObservePathMkdir,
		p.HideoutObservePathRename,
		p.HideoutObservePathRmdir,
		p.HideoutObservePathSymlink,
		p.HideoutObservePathTruncate,
		p.HideoutObservePathUnlink,
		p.HideoutObserveVfsRead,
		p.HideoutObserveVfsReadv,
		p.HideoutObserveVfsWrite,
		p.HideoutObserveVfsWritev,
	)
}

func _FileObserverClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed file_observer_bpfel.o
var _FileObserverBytes []byte
