// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type networkObserverForkParent struct {
	_            structs.HostLayout
	Pid          uint32
	_            [4]byte
	ExecSequence uint64
}

type networkObserverNetworkCollectorCounters struct {
	_                    structs.HostLayout
	MatchedEvents        uint64
	ReservedEvents       uint64
	RingbufDrops         uint64
	StateDrops           uint64
	CorrelationHits      uint64
	CorrelationMisses    uint64
	UnsupportedEvents    uint64
	DnsMatchedPackets    uint64
	DnsReservedPackets   uint64
	DnsRingbufDrops      uint64
	DnsCaptureFailures   uint64
	DnsTruncatedPackets  uint64
	DnsStateMisses       uint64
	ProxyMatchedPackets  uint64
	ProxyReservedChunks  uint64
	ProxyRingbufDrops    uint64
	ProxyCaptureFailures uint64
	ProxyTruncatedChunks uint64
	ProxyStateMisses     uint64
	ProxyCompletedSkips  uint64
	ProxyBudgetExhausted uint64
}

type networkObserverNetworkSocketState struct {
	_                 structs.HostLayout
	Kind              uint32
	Pid               uint32
	ExecutionPid      uint32
	Uid               uint32
	Gid               uint32
	Family            uint32
	Protocol          uint32
	DestinationPort   uint32
	Ifindex           uint32
	_                 [4]byte
	ObserverSequence  uint64
	ExecSequence      uint64
	CgroupId          uint64
	EgressPackets     uint64
	EgressBytes       uint64
	ProxyCaptureBytes uint64
	Address           [16]uint8
}

type networkObserverProxyEndpointKey struct {
	_       structs.HostLayout
	Family  uint32
	Port    uint32
	Address [16]uint8
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	networkObserverMapDnsPacketEvents          = "dns_packet_events"
	networkObserverMapExecSequences            = "exec_sequences"
	networkObserverMapNetworkCounters          = "network_counters"
	networkObserverMapNetworkObservationEvents = "network_observation_events"
	networkObserverMapNetworkSocketStates      = "network_socket_states"
	networkObserverMapObserverSequences        = "observer_sequences"
	networkObserverMapProxyCompletedSockets    = "proxy_completed_sockets"
	networkObserverMapProxyEndpoints           = "proxy_endpoints"
	networkObserverMapProxyHandshakeEvents     = "proxy_handshake_events"
	networkObserverProgHideoutCorrelateEgress  = "hideout_correlate_egress"
	networkObserverProgHideoutObserveConnect4  = "hideout_observe_connect4"
	networkObserverProgHideoutObserveConnect6  = "hideout_observe_connect6"
	networkObserverProgHideoutObserveIngress   = "hideout_observe_ingress"
	networkObserverProgHideoutObserveSendmsg4  = "hideout_observe_sendmsg4"
	networkObserverProgHideoutObserveSendmsg6  = "hideout_observe_sendmsg6"
	networkObserverVarDnsEncryptedPort         = "dns_encrypted_port"
	networkObserverVarDnsPlaintextPort         = "dns_plaintext_port"
	networkObserverVarNetworkTargetCgroupId    = "network_target_cgroup_id"
)

// loadNetworkObserver returns the embedded CollectionSpec for networkObserver.
func loadNetworkObserver() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_NetworkObserverBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load networkObserver: %w", err)
	}

	return spec, err
}

// loadNetworkObserverObjects loads networkObserver and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*networkObserverObjects
//	*networkObserverPrograms
//	*networkObserverMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadNetworkObserverObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadNetworkObserver()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// networkObserverSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type networkObserverSpecs struct {
	networkObserverProgramSpecs
	networkObserverMapSpecs
	networkObserverVariableSpecs
}

// networkObserverProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type networkObserverProgramSpecs struct {
	HideoutCorrelateEgress *ebpf.ProgramSpec `ebpf:"hideout_correlate_egress"`
	HideoutObserveConnect4 *ebpf.ProgramSpec `ebpf:"hideout_observe_connect4"`
	HideoutObserveConnect6 *ebpf.ProgramSpec `ebpf:"hideout_observe_connect6"`
	HideoutObserveIngress  *ebpf.ProgramSpec `ebpf:"hideout_observe_ingress"`
	HideoutObserveSendmsg4 *ebpf.ProgramSpec `ebpf:"hideout_observe_sendmsg4"`
	HideoutObserveSendmsg6 *ebpf.ProgramSpec `ebpf:"hideout_observe_sendmsg6"`
}

// networkObserverMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type networkObserverMapSpecs struct {
	DnsPacketEvents          *ebpf.MapSpec `ebpf:"dns_packet_events"`
	ExecSequences            *ebpf.MapSpec `ebpf:"exec_sequences"`
	NetworkCounters          *ebpf.MapSpec `ebpf:"network_counters"`
	NetworkObservationEvents *ebpf.MapSpec `ebpf:"network_observation_events"`
	NetworkSocketStates      *ebpf.MapSpec `ebpf:"network_socket_states"`
	ObserverSequences        *ebpf.MapSpec `ebpf:"observer_sequences"`
	ProxyCompletedSockets    *ebpf.MapSpec `ebpf:"proxy_completed_sockets"`
	ProxyEndpoints           *ebpf.MapSpec `ebpf:"proxy_endpoints"`
	ProxyHandshakeEvents     *ebpf.MapSpec `ebpf:"proxy_handshake_events"`
}

// networkObserverVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type networkObserverVariableSpecs struct {
	DnsEncryptedPort      *ebpf.VariableSpec `ebpf:"dns_encrypted_port"`
	DnsPlaintextPort      *ebpf.VariableSpec `ebpf:"dns_plaintext_port"`
	NetworkTargetCgroupId *ebpf.VariableSpec `ebpf:"network_target_cgroup_id"`
}

// networkObserverObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadNetworkObserverObjects or ebpf.CollectionSpec.LoadAndAssign.
type networkObserverObjects struct {
	networkObserverPrograms
	networkObserverMaps
	networkObserverVariables
}

func (o *networkObserverObjects) Close() error {
	return _NetworkObserverClose(
		&o.networkObserverPrograms,
		&o.networkObserverMaps,
	)
}

// networkObserverMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadNetworkObserverObjects or ebpf.CollectionSpec.LoadAndAssign.
type networkObserverMaps struct {
	DnsPacketEvents          *ebpf.Map `ebpf:"dns_packet_events"`
	ExecSequences            *ebpf.Map `ebpf:"exec_sequences"`
	NetworkCounters          *ebpf.Map `ebpf:"network_counters"`
	NetworkObservationEvents *ebpf.Map `ebpf:"network_observation_events"`
	NetworkSocketStates      *ebpf.Map `ebpf:"network_socket_states"`
	ObserverSequences        *ebpf.Map `ebpf:"observer_sequences"`
	ProxyCompletedSockets    *ebpf.Map `ebpf:"proxy_completed_sockets"`
	ProxyEndpoints           *ebpf.Map `ebpf:"proxy_endpoints"`
	ProxyHandshakeEvents     *ebpf.Map `ebpf:"proxy_handshake_events"`
}

func (m *networkObserverMaps) Close() error {
	return _NetworkObserverClose(
		m.DnsPacketEvents,
		m.ExecSequences,
		m.NetworkCounters,
		m.NetworkObservationEvents,
		m.NetworkSocketStates,
		m.ObserverSequences,
		m.ProxyCompletedSockets,
		m.ProxyEndpoints,
		m.ProxyHandshakeEvents,
	)
}

// networkObserverVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadNetworkObserverObjects or ebpf.CollectionSpec.LoadAndAssign.
type networkObserverVariables struct {
	DnsEncryptedPort      *ebpf.Variable `ebpf:"dns_encrypted_port"`
	DnsPlaintextPort      *ebpf.Variable `ebpf:"dns_plaintext_port"`
	NetworkTargetCgroupId *ebpf.Variable `ebpf:"network_target_cgroup_id"`
}

// networkObserverPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadNetworkObserverObjects or ebpf.CollectionSpec.LoadAndAssign.
type networkObserverPrograms struct {
	HideoutCorrelateEgress *ebpf.Program `ebpf:"hideout_correlate_egress"`
	HideoutObserveConnect4 *ebpf.Program `ebpf:"hideout_observe_connect4"`
	HideoutObserveConnect6 *ebpf.Program `ebpf:"hideout_observe_connect6"`
	HideoutObserveIngress  *ebpf.Program `ebpf:"hideout_observe_ingress"`
	HideoutObserveSendmsg4 *ebpf.Program `ebpf:"hideout_observe_sendmsg4"`
	HideoutObserveSendmsg6 *ebpf.Program `ebpf:"hideout_observe_sendmsg6"`
}

func (p *networkObserverPrograms) Close() error {
	return _NetworkObserverClose(
		p.HideoutCorrelateEgress,
		p.HideoutObserveConnect4,
		p.HideoutObserveConnect6,
		p.HideoutObserveIngress,
		p.HideoutObserveSendmsg4,
		p.HideoutObserveSendmsg6,
	)
}

func _NetworkObserverClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed network_observer_bpfel.o
var _NetworkObserverBytes []byte
