// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type observerCollectorCounters struct {
	_              structs.HostLayout
	MatchedEvents  uint64
	ReservedEvents uint64
	RingbufDrops   uint64
	StateDrops     uint64
}

type observerForkParent struct {
	_            structs.HostLayout
	Pid          uint32
	_            [4]byte
	ExecSequence uint64
}

type observerPendingExec struct {
	_          structs.HostLayout
	Executable [128]int8
	Argc       uint32
	Flags      uint32
	Argv       [4][64]int8
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	observerMapExecSequences               = "exec_sequences"
	observerMapForkParents                 = "fork_parents"
	observerMapNextExecSequence            = "next_exec_sequence"
	observerMapObservationEvents           = "observation_events"
	observerMapObserverSequences           = "observer_sequences"
	observerMapPendingExecScratch          = "pending_exec_scratch"
	observerMapPendingExecs                = "pending_execs"
	observerMapProcessCounters             = "process_counters"
	observerProgHideoutCaptureExecArgv     = "hideout_capture_exec_argv"
	observerProgHideoutCaptureExecveatArgv = "hideout_capture_execveat_argv"
	observerProgHideoutObserveProcessExec  = "hideout_observe_process_exec"
	observerProgHideoutObserveProcessExit  = "hideout_observe_process_exit"
	observerProgHideoutObserveProcessFork  = "hideout_observe_process_fork"
	observerVarTargetCgroupId              = "target_cgroup_id"
)

// loadObserver returns the embedded CollectionSpec for observer.
func loadObserver() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_ObserverBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load observer: %w", err)
	}

	return spec, err
}

// loadObserverObjects loads observer and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*observerObjects
//	*observerPrograms
//	*observerMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadObserverObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadObserver()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// observerSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type observerSpecs struct {
	observerProgramSpecs
	observerMapSpecs
	observerVariableSpecs
}

// observerProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type observerProgramSpecs struct {
	HideoutCaptureExecArgv     *ebpf.ProgramSpec `ebpf:"hideout_capture_exec_argv"`
	HideoutCaptureExecveatArgv *ebpf.ProgramSpec `ebpf:"hideout_capture_execveat_argv"`
	HideoutObserveProcessExec  *ebpf.ProgramSpec `ebpf:"hideout_observe_process_exec"`
	HideoutObserveProcessExit  *ebpf.ProgramSpec `ebpf:"hideout_observe_process_exit"`
	HideoutObserveProcessFork  *ebpf.ProgramSpec `ebpf:"hideout_observe_process_fork"`
}

// observerMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type observerMapSpecs struct {
	ExecSequences      *ebpf.MapSpec `ebpf:"exec_sequences"`
	ForkParents        *ebpf.MapSpec `ebpf:"fork_parents"`
	NextExecSequence   *ebpf.MapSpec `ebpf:"next_exec_sequence"`
	ObservationEvents  *ebpf.MapSpec `ebpf:"observation_events"`
	ObserverSequences  *ebpf.MapSpec `ebpf:"observer_sequences"`
	PendingExecScratch *ebpf.MapSpec `ebpf:"pending_exec_scratch"`
	PendingExecs       *ebpf.MapSpec `ebpf:"pending_execs"`
	ProcessCounters    *ebpf.MapSpec `ebpf:"process_counters"`
}

// observerVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type observerVariableSpecs struct {
	TargetCgroupId *ebpf.VariableSpec `ebpf:"target_cgroup_id"`
}

// observerObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadObserverObjects or ebpf.CollectionSpec.LoadAndAssign.
type observerObjects struct {
	observerPrograms
	observerMaps
	observerVariables
}

func (o *observerObjects) Close() error {
	return _ObserverClose(
		&o.observerPrograms,
		&o.observerMaps,
	)
}

// observerMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadObserverObjects or ebpf.CollectionSpec.LoadAndAssign.
type observerMaps struct {
	ExecSequences      *ebpf.Map `ebpf:"exec_sequences"`
	ForkParents        *ebpf.Map `ebpf:"fork_parents"`
	NextExecSequence   *ebpf.Map `ebpf:"next_exec_sequence"`
	ObservationEvents  *ebpf.Map `ebpf:"observation_events"`
	ObserverSequences  *ebpf.Map `ebpf:"observer_sequences"`
	PendingExecScratch *ebpf.Map `ebpf:"pending_exec_scratch"`
	PendingExecs       *ebpf.Map `ebpf:"pending_execs"`
	ProcessCounters    *ebpf.Map `ebpf:"process_counters"`
}

func (m *observerMaps) Close() error {
	return _ObserverClose(
		m.ExecSequences,
		m.ForkParents,
		m.NextExecSequence,
		m.ObservationEvents,
		m.ObserverSequences,
		m.PendingExecScratch,
		m.PendingExecs,
		m.ProcessCounters,
	)
}

// observerVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadObserverObjects or ebpf.CollectionSpec.LoadAndAssign.
type observerVariables struct {
	TargetCgroupId *ebpf.Variable `ebpf:"target_cgroup_id"`
}

// observerPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadObserverObjects or ebpf.CollectionSpec.LoadAndAssign.
type observerPrograms struct {
	HideoutCaptureExecArgv     *ebpf.Program `ebpf:"hideout_capture_exec_argv"`
	HideoutCaptureExecveatArgv *ebpf.Program `ebpf:"hideout_capture_execveat_argv"`
	HideoutObserveProcessExec  *ebpf.Program `ebpf:"hideout_observe_process_exec"`
	HideoutObserveProcessExit  *ebpf.Program `ebpf:"hideout_observe_process_exit"`
	HideoutObserveProcessFork  *ebpf.Program `ebpf:"hideout_observe_process_fork"`
}

func (p *observerPrograms) Close() error {
	return _ObserverClose(
		p.HideoutCaptureExecArgv,
		p.HideoutCaptureExecveatArgv,
		p.HideoutObserveProcessExec,
		p.HideoutObserveProcessExit,
		p.HideoutObserveProcessFork,
	)
}

func _ObserverClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed observer_bpfel.o
var _ObserverBytes []byte
